import torch 
import torch.nn as nn 
import torch.nn.functional as F 
import torch.utils.data import DataLoader
import torchvision import datasets, transforms 


# basic cnn 

def SimpleCNN(nn.Module):
    def __init__(self):
        super().__init__()
         
        self.conv1 = nn.Conv2d(1,32,3) # why? 
        # because input image is 28x28, after conv1 it becomes 26x26
        # so after pooling it becomes 13x13
        self.conv2 = nn.Conv2d(32, 64, 3)
        # after conv2 it becomes 11x11
        self.pool = nn.MaxPool2d(2,2)
        # after pooling it becomes 5x5
        self.fc1 = nn.Linear(64 * 5 * 5, 120) # why this size? 
        # because after conv and pool, the feature map size is 64 channels of 5x5
        # after fc1 it becomes 120
        # channels here mean feature maps which are generated by filters doing convolution
        self.fc2 = nn.Linear(128, 10)
        
    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x))) # why relu? 
        # beacuse relu introduces non-linearity
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 64 * 5 * 5) # flatten the tensor 
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

model
